from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'HotelBooking',
    'FlightBooking',
    'Thread',
    'ChatMessage',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'HotelBooking': {
    },
    'FlightBooking': {
    },
    'Thread': {
        'messages': 'ChatMessage',
    },
    'ChatMessage': {
        'thread': 'Thread',
    },
}

# fmt: on